---

- name: Run Filter to Gather File Facts
  set_fact:
    file_facts: "{{ path | check_file_location(tmp_inv_dir) }}"

- name: "Set default values"
  set_fact:
    oc_option_f: "{{ file_facts['oc_option_f'] }}"
    oc_file_path: "{{ file_facts['oc_file_path'] }}"
    oc_process_local: "{{ file_facts['oc_process_local'] }}"

